export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';

export const GET_LAST_EVENT = 'GET_LAST_EVENT';
export const GET_LAST_EVENT_SUCCESS = 'GET_LAST_EVENT_SUCCESS';

export const GET_NEXT_EVENT = 'GET_NEXT_EVENT';
export const GET_NEXT_EVENT_SUCCESS = 'GET_NEXT_EVENT_SUCCESS';

export const REMOVE_EVENT = 'REMOVE_EVENT';

export const GET_CAMERA_RTSP_PORT = 'GET_CAMERA_RTSP_PORT';
export const GET_CAMERA_RTSP_PORT_SUCCESS = 'GET_CAMERA_RTSP_PORT_SUCCESS';

export const GET_VA_RTSP_PORT = 'GET_VA_RTSP_PORT';
export const GET_VA_RTSP_PORT_SUCCESS = 'GET_VA_RTSP_PORT_SUCCESS';

export const CHECK_STREAM = 'CHECK_STREAM';
export const CHECK_STREAM_SUCCESS = 'CHECK_STREAM_SUCCESS';

export const START_STREAM = 'START_STREAM';
export const START_STREAM_SUCCESS = 'START_STREAM_SUCCESS';

export const CREATE_STREAM = 'CREATE_STREAM';
export const CREATE_STREAM_SUCCESS = 'CREATE_STREAM_SUCCESS';

export const INITIAL_PLAYER = 'INITIAL_PLAYER';

export const GET_STREAM_URL = 'GET_STREAM_URL';
export const GET_STREAM_URL_SUCCESS = 'GET_STREAM_URL_SUCCESS';